### ISSUE TITLE
Scope rules are not obeyed

### ISSUE THREAD

**Issue by primoz-k** [internetarchive/brozzler#37]
Hello!

[job-conf.rst](https://github.com/internetarchive/brozzler/blob/master/job-conf.rst) lacks info about scope rules so I did my best to try to define them in my `job.yml`:

```
id: myjob
time_limit: 60 # seconds
scope:
  surt: http://(com,site,www,)/wanted-path
seeds:
  - url: https://www.site.com
```

If I understand correctly, brozzler should find all links i.e. `https://www.site.com/wanted-path/extra` and crawl only links with `wanted-path` in them. Is this correct?

The problem I have is that Brozzler crawls all links i.e. `https://www.site.com/other-path`, but I don't want that. Is the problem with my config or does brozzler ignore path of provided surt?
